server:
  port: 8125

spring:
  application:
    name: matadata
#
#  data:
#    elasticsearch:
#      cluster-name: my-application
#      cluster-nodes: 127.0.0.1:9300
#      repositories:
#        enabled: true