server:
  port: 7002
eureka:
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 1000
  instance:
    hostname: eureka7002.com
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7003.com:7003/eureka/

spring:
  application:
    name: microservice-eureka