server:
  port: 9527
spring:
  application:
    name: microservice-zuul-gateway-9527
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: myzuul.com
    prefer-ip-address: true
zuul:
  ignored-services: microservice-dept
  routes:
    mydept.serviceId: MICROSERVICE-DEPT
    mydept.path: /mydept/**
info:
  app.name: microservice
  company.name: www.ldw.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$