package com.ldw.microservice.dto;

import com.deepexi.data.metadata.domain.eo.SuperEntity;
import lombok.Data;
import lombok.ToString;

import java.io.Serializable;
import java.util.Date;

/**
 * ClassName:TaskMetadataCollectionVO <br/>
 * Function: 元数据采集任务VO对象. <br/>
 * Reason: . <br/>
 * Date: 2020年10月9日 下午2:52:10 <br/>
 *
 * @author ldw
 * @see
 * @since JDK 1.8
 */
@Data
@ToString
public class UpdateTaskInfoDTO extends SuperEntity implements Serializable {

    /**
     * @desc 用户Id
     */
    private Long userId;
    /**
     * @desc 数据源类型：oracle-oracle；hive-hive；impala-impala
     */
    private String dataSourceType;

    /**
     * @desc 数据源id
     */
    private Long dataSourceId;
    /**
     * @desc 数据源名称
     */
    private String dataSourceName;
    /**
     * @desc 数据源环境类型（开发0、生产1、基础环境2）
     */
    private Integer dataSourceEnv;
    /**
     * external_datasource_info表主键ID
     */
//    private Long externalDatasourceInfoId;

    /**
     * @desc 采集周期：0-小时；1-天；2-周；3-月；4-手动采集
     */
    private Integer collectionPeriod;

    /**
     * @desc 生效日期开始时间
     */
    private Date beginEffectiveDate;

    /**
     * @desc 生效日期结束时间
     */
    private Date endEffectiveDate;

    /**
     * @desc 按小时采集开始时间小时
     */
    private Integer hourBeginTime;

    /**
     * @desc 按小时采集开始时间分钟
     */
    private Integer minuteBeginTime;

    /**
     * @desc 按小时采集结束时间小时
     */
    private Integer hourEndTime;

    /**
     * @desc 按小时采集结束时间分钟
     */
    private Integer minuteEndTime;

    /**
     * @desc 按小时采集间隔时间
     */
    private Integer intervalCollectionTime;

    /**
     * @desc 采集时间小时
     */
    private Integer hourCollectionTime;

    /**
     * @desc 采集时间分钟
     */
    private Integer minuteCollectionTime;

    /**
     * @desc 按周采集的指定日期：1-周一；2-周二；3-周三；4-周四；5-周五；6-周六；7-周日
     */
    private Integer specifiedDateWeekly;

    /**
     * @desc 按月采集的指定日期：1-1；2-2；3-3 ......
     */
    private Integer specifiedDateMonthly;

    /**
     * Database Column Remarks: 任务执行时间
     * <p>
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column task_log.executed_time
     *
     * @mbg.generated
     */
    private Date executedTime;
    /**
     * @desc 执行时长（单位：毫秒ms）
     */
    private Long timeConsuming;

    /**
     * Database Column Remarks: 任务配置
     * <p>
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column task_info.config
     *
     * @mbg.generated
     */
    private String config;

    /**
     * Database Column Remarks: 任务状态：0-未启动；1-运行中；2-启动失败；3-停止了；4-运行成功；5-运行失败；6-已失效
     * <p>
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column task_info.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     * @desc 任务执行结果信息
     */
    private String message;

    /**
     * @desc 项目Id
     */
    private Long projectId;
    /**
     * @desc 调度程序的回调url地址
     */
    private String callbackUrlScheduler;
    /**
     * @desc 任务执行信息详情
     */
    private String messageDetail;

    /**
     * @desc 关联类型(1 : 外部数据源 ; 2 : 计算资源)
     */
    private Integer relType;

}
