version: '3.8'

services:
  microservice-uc:
    image: microservice-uc:latest
    container_name: microservice-uc
    restart: always
    ports:
      - "8001:8001"

  microservice-order:
    image: microservice-order:latest
    container_name: microservice-order
    restart: always
    ports:
      - "8002:8002"

  service-product:
    image: your-dockerhub-username/service-product:latest
    container_name: service-product
    restart: always
    ports:
      - "8083:8080"

volumes:
  mysql_data:
