server:
  port: 8001

spring:
  profiles:
    active: test
---
#开发环境配置
spring:
  profiles: dev
  application:
    name:  microservice_dept_dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/huobi_pool?characterEncoding=utf8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT
    username: root
    password: aaaaa888
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservice_dept_8001
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 10

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.ldw.microservice.entity
  mapper-locations: mybatis/mapper/**/*.xml

---
#测试环境配置
spring:
  profiles: test
  application:
    name:  microservice_dept_test
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/huobi_pool?characterEncoding=utf8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT
    username: root
    password: aaaa66a888
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservice_dept_8001
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 10

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.ldw.microservice.entity
  mapper-locations: mybatis/mapper/**/*.xml





#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/cloudDB01?serverTimezone=UTC
#    username: root
#    password: aaaaa888

