server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.ldw.microservice.entity
  mapper-locations: mybatis/mapper/**/*.xml
spring:
  application:
    name: microservice-dept
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01?serverTimezone=UTC
    username: root
    password: aaaaa888
eureka:
  client:
    healthcheck:
      enabled: true   #开启健康检查（需要spring-boot-starter-actuator依赖）
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservice_dept_8001
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 10
info:
  app.name: microservice
  company.name: www.ldw.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
