server:
  port: 8002
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.ldw.microservice.entity
  mapper-locations: mybatis/mapper/**/*.xml
spring:
  application:
    name: microservice-dept
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudDB02?serverTimezone=UTC
    username: root
    password: aaaaa888
  devtools:
    restart:
      enabled: true    #设置开启热部署
      additional-paths: src/main/java #重启目录
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservice_dept_8002
    prefer-ip-address: true
info:
  app.name: microservice
  company.name: www.ldw.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

