server:
  port: 80
#feign:
#  hystrix:
#    enabled: true
#eureka:
#  client:
#    register-with-eureka: false
#    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.ldw.microservice.entity
  mapper-locations: mybatis/mapper/**/*.xml
spring:
  application:
    name: microservice-dept
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudDB02?serverTimezone=UTC
    username: root
    password: aaaaa888

