server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 1000
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

spring:
  application:
    name: microservice-eureka