server:
  port: 7001

spring:
  profiles:
    active: ${eureka_env_name}
---
spring:
  profiles: test-21           # 指定profile=peer1
  application:
    name: Eureka-Server
server:
  port: 7001  # 注册服务的端口号
eureka:
  instance:
    hostname: peer1                # 指定当profile=peer1时，主机名
  client:
    serviceUrl:
      defaultZone: http://peer2:7001/eureka/   # 将自己注册到peer2这个Eureka上面去

---
spring:
  profiles: test-23
  application:
    name: Eureka-Server
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:7001/eureka/ # 服务注册地址，将自己注册到peer2上去