#服务启动端口的配置
server:
  port: 9528

# eureka 的相关配置
# 如果不需要 结合eureka 使用，可以不要这一段配置
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true     # 是否注册到eureka
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    prefer-ip-address: true
    hostname: microservice-gateway
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health

spring:
  #redis
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    open: true
    key-prefix: coral:gateway
    expire: 30
  cloud:
    #   gateway相关配置
    gateway:
      # 配置允许跨域请求
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
      #    路由定义   也可以通过类定义
      routes:
        - id: baidu
          uri: https://www.baidu.com
          predicates:
            - Path=/baidu/**
          filters:
            - StripPrefix=1

        - id: eureka-manage
          uri: lb://microservice-dept
          predicates:
            - Path=/eureka-manage/**
          filters:
            - StripPrefix=1

        - id: gate-way-service
          uri: lb://microservice-gateway
          predicates:
            - Path=/gate-service/**
          filters:
            - StripPrefix=1

  application:
    name: microservice-gateway
management:
  endpoints:
    web:
      exposure:
        include: "*"      #配置说明：management.endpoints.web.exposure.include 暴露所有的gateway端点
  endpoint:
    health:
      show-details: ALWAYS