#服务启动端口的配置
server:
  port: 9527

# eureka 的相关配置
# 如果不需要 结合eureka 使用，可以不要这一段配置
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true     # 是否注册到eureka
    service-url:
      defaultZone: http://peer1:7001/eureka/,http://peer2:7001/eureka/
  instance:
    prefer-ip-address: true
    hostname: microservice-gateway


spring:
  cloud:
    #   gateway相关配置
    gateway:
      # 配置允许跨域请求
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
      #    路由定义   也可以通过类定义
      routes:
        - id: baidu
          uri: https://www.baidu.com
          predicates:
            - Path=/baidu/**
          filters:
            - StripPrefix=1

        - id: eureka-manage
          uri: lb://microservice-dept
          predicates:
            - Path=/eureka-manage/**
          filters:
            - StripPrefix=1

        - id: gate-way-service
          uri: lb://microservice-gateway
          predicates:
            - Path=/gate-service/**
          filters:
            - StripPrefix=1

  application:
    name: microservice-gateway
